// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxsgOsR8w33ArDje-S40HgjRgcd-SMLs8',
    appId: '1:209067531240:web:b52e26ed4fefb411a8625d',
    messagingSenderId: '209067531240',
    projectId: 'air-chat-5552f',
    authDomain: 'air-chat-5552f.firebaseapp.com',
    storageBucket: 'air-chat-5552f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-2PZ2Ch7QqMpnGmW1Gb9vLUTwKqg9bt0',
    appId: '1:209067531240:android:ad34bf0cc29cf399a8625d',
    messagingSenderId: '209067531240',
    projectId: 'air-chat-5552f',
    storageBucket: 'air-chat-5552f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDEH-DK3pojIy8nrhXIPOTHM5lsxe1b4I',
    appId: '1:209067531240:ios:4d212faab07825fca8625d',
    messagingSenderId: '209067531240',
    projectId: 'air-chat-5552f',
    storageBucket: 'air-chat-5552f.appspot.com',
    iosBundleId: 'com.vishal.airChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDEH-DK3pojIy8nrhXIPOTHM5lsxe1b4I',
    appId: '1:209067531240:ios:4d212faab07825fca8625d',
    messagingSenderId: '209067531240',
    projectId: 'air-chat-5552f',
    storageBucket: 'air-chat-5552f.appspot.com',
    iosBundleId: 'com.vishal.airChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxsgOsR8w33ArDje-S40HgjRgcd-SMLs8',
    appId: '1:209067531240:web:094efeb55a1f4db2a8625d',
    messagingSenderId: '209067531240',
    projectId: 'air-chat-5552f',
    authDomain: 'air-chat-5552f.firebaseapp.com',
    storageBucket: 'air-chat-5552f.appspot.com',
  );
}
